import { execFileSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';

// ---------------------------------------------------------------------------
// CLAUDE.md template generator
// ---------------------------------------------------------------------------

interface ClaudeMdVars {
  alias: string;
  wwuid: string;
  remote: string | null;
}

export function generateClaudeMd({ alias, wwuid, remote }: ClaudeMdVars): string {
  const now = new Date().toISOString().slice(0, 10);
  return `# CLAUDE.md — ${alias} Town

**Town:** ${alias}
**Scope:** town
**Version:** 0.1.0

---

## 1. Identity

| Field | Value |
|---|---|
| **wwuid** | \`${wwuid}\` |
| **Alias** | \`${alias}\` |
| **Remote** | \`${remote ?? '(not set)'}\` |
| **County Law** | *(set path to county CLAUDE.md)* |

---

## 2. Active Roles

| Role | Actor | Scope | Authority |
|---|---|---|---|
| *(declare roles here)* | | | |

---

## 3. Cold-Start Checklist

Every new Copilot window must:

1. **Read this file** ✓
2. **Read county law** — *(set county CLAUDE.md path)*
3. **Send session-open memo** — \`.wildwest/telegraph/\`
4. **Process telegraph inbox** — resolve unprocessed memos
5. **Check git status** — \`git status\` and \`git log --oneline -5\`
6. **Review TODO.md** — open work and blockers

---

## 4. Key Paths

| Path | Purpose |
|---|---|
| \`.wildwest/registry.json\` | Town identity + scope declaration |
| \`.wildwest/telegraph/\` | Inbox — memos, requests, notifications |
| \`.wildwest/board/branches/\` | Branch lifecycle tracker |
| \`TODO.md\` | Open work and blockers |
| \`DONE.md\` | Completed work log |

---

## 5. Telegraph Rules (Rule 23)

Every telegraph inbox must be processed before session end.

### Memo Naming Convention

- **Inbound:** \`YYYYMMDD-HHMMz-to-<role>-from-<role>--subject.md\`
- **Outbound (response):** \`YYYYMMDD-HHMMz-to-<role>-from-<role>--subject-resolved.md\`

---

## 6. Open Work

See \`TODO.md\` for full board.

---

## 7. Quick Commands

\`\`\`bash
# Check git status
git status
git log --oneline -5

# View telegraph inbox
ls -la .wildwest/telegraph/
\`\`\`

---

**Last Updated:** ${now}
**Generated by:** wildwest-vscode initTown
`;
}

export function generateCountyClaudeMd({ alias, wwuid, remote }: ClaudeMdVars): string {
  const now = new Date().toISOString().slice(0, 10);
  return `# CLAUDE.md — ${alias} County

**County:** ${alias}
**Scope:** county
**Version:** 0.1.0

---

## 1. Identity

| Field | Value |
|---|---|
| **wwuid** | \`${wwuid}\` |
| **Alias** | \`${alias}\` |
| **Remote** | \`${remote ?? '(not set)'}\` |
| **Territory Law** | *(set path to territory CLAUDE.md)* |

---

## 2. Active Roles

| Role | Actor | Scope | Authority |
|---|---|---|---|
| *(declare roles here)* | | | |

---

## 3. Cold-Start Checklist

Every new Copilot window must:

1. **Read this file** ✓
2. **Read territory law** — *(set territory CLAUDE.md path)*
3. **Send session-open memo** — \`.wildwest/telegraph/\`
4. **Process telegraph inbox** — resolve unprocessed memos
5. **Check git status** — \`git status\` and \`git log --oneline -5\`
6. **Review TODO.md** — open work and blockers

---

## 4. Key Paths

| Path | Purpose |
|---|---|
| \`.wildwest/registry.json\` | County identity + scope declaration |
| \`.wildwest/telegraph/\` | Inbox — memos, requests, notifications |
| \`TODO.md\` | Open work and blockers |
| \`DONE.md\` | Completed work log |

---

## 5. Telegraph Rules (Rule 23)

Every telegraph inbox must be processed before session end.

### Memo Naming Convention

- **Inbound:** \`YYYYMMDD-HHMMz-to-<role>-from-<role>--subject.md\`
- **Outbound:** \`YYYYMMDD-HHMMz-to-<role>-from-<role>--subject-resolved.md\`

---

## 6. Open Work

See \`TODO.md\` for full board.

---

## 7. Quick Commands

\`\`\`bash
git status
git log --oneline -5
ls -la .wildwest/telegraph/
\`\`\`

---

**Last Updated:** ${now}
**Generated by:** wildwest-vscode initCounty
`;
}

export function generateTerritoryClaudeMd({ alias, wwuid, remote }: ClaudeMdVars): string {
  const now = new Date().toISOString().slice(0, 10);
  return `# CLAUDE.md — ${alias} Territory

**Territory:** ${alias}
**Scope:** territory
**Version:** 0.1.0

---

## 1. Identity

| Field | Value |
|---|---|
| **wwuid** | \`${wwuid}\` |
| **Alias** | \`${alias}\` |
| **Remote** | \`${remote ?? '(not set)'}\` |

---

## 2. Active Roles

| Role | Actor | Scope | Authority |
|---|---|---|---|
| *(declare roles here)* | | | |

---

## 3. Cold-Start Checklist

Every new Copilot window must:

1. **Read this file** ✓
2. **Send session-open memo** — \`.wildwest/telegraph/\`
3. **Process telegraph inbox** — resolve unprocessed memos
4. **Check git status** — \`git status\` and \`git log --oneline -5\`
5. **Review TODO.md** — open work and blockers

---

## 4. Key Paths

| Path | Purpose |
|---|---|
| \`.wildwest/registry.json\` | Territory identity + scope declaration |
| \`.wildwest/telegraph/\` | Inbox — memos, requests, notifications |
| \`TODO.md\` | Open work and blockers |
| \`DONE.md\` | Completed work log |

---

## 5. Telegraph Rules (Rule 23)

Every telegraph inbox must be processed before session end.

### Memo Naming Convention

- **Inbound:** \`YYYYMMDD-HHMMz-to-<role>-from-<role>--subject.md\`
- **Outbound:** \`YYYYMMDD-HHMMz-to-<role>-from-<role>--subject-resolved.md\`

---

## 6. Open Work

See \`TODO.md\` for full board.

---

## 7. Quick Commands

\`\`\`bash
git status
git log --oneline -5
ls -la .wildwest/telegraph/
\`\`\`

---

**Last Updated:** ${now}
**Generated by:** wildwest-vscode initTerritory
`;
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

function generateHookConfig(port: number): Record<string, unknown> {
  const baseUrl = `http://localhost:${port}/hooks/claude`;
  return {
    hooks: {
      Stop: [
        {
          hooks: [
            {
              type: 'command',
              command: `curl -sf -X POST ${baseUrl}/stop -H 'Content-Type: application/json' -d '{}' || true`,
            },
          ],
        },
      ],
      PostToolUse: [
        {
          matcher: 'Write|Edit|MultiEdit',
          hooks: [
            {
              type: 'command',
              command: `curl -sf -X POST ${baseUrl}/file-changed -H 'Content-Type: application/json' -d '{}' || true`,
            },
          ],
        },
      ],
    },
  };
}

function writeClaudeSettings(repoRoot: string, port: number, log: (msg: string) => void): void {
  const claudeDir = path.join(repoRoot, '.claude');
  const claudeSettingsPath = path.join(claudeDir, 'settings.json');
  fs.mkdirSync(claudeDir, { recursive: true });
  if (!fs.existsSync(claudeSettingsPath)) {
    fs.writeFileSync(claudeSettingsPath, JSON.stringify(generateHookConfig(port), null, 2) + '\n');
    log(`created .claude/settings.json (hooks → port ${port})`);
  } else {
    log('.claude/settings.json already exists — skipped (no overwrite)');
  }
}

function updateGitignore(repoRoot: string, entries: string[], log: (msg: string) => void): void {
  const gitignorePath = path.join(repoRoot, '.gitignore');
  const existing = fs.existsSync(gitignorePath) ? fs.readFileSync(gitignorePath, 'utf8') : '';
  let updated = existing;
  for (const entry of entries) {
    if (!updated.includes(entry)) {
      const sep = updated.endsWith('\n') || updated === '' ? '' : '\n';
      updated = `${updated}${sep}${entry}\n`;
    }
  }
  if (updated !== existing) {
    fs.writeFileSync(gitignorePath, updated);
    log(`updated .gitignore (added: ${entries.join(', ')})`);
  } else {
    log('.gitignore already up to date');
  }
}

function createTelegraphDirs(wildwestDir: string, log: (msg: string) => void): void {
  for (const sub of [
    'telegraph',
    'telegraph/inbox',
    'telegraph/outbox',
    'telegraph/outbox/history',
    'telegraph/history',
  ]) {
    fs.mkdirSync(path.join(wildwestDir, sub), { recursive: true });
  }
  fs.writeFileSync(path.join(wildwestDir, 'telegraph', '.gitkeep'), '');
  log('created telegraph dir structure');
}

export async function initTown(outputChannel: vscode.OutputChannel): Promise<void> {
  const folders = vscode.workspace.workspaceFolders;
  if (!folders || folders.length === 0) {
    vscode.window.showErrorMessage('Wild West: no workspace folder open.');
    return;
  }

  // ── Folder selection — always show picker so user confirms the target ─────
  const pick = await vscode.window.showQuickPick(
    folders.map((f) => ({ label: f.name, description: f.uri.fsPath, folder: f })),
    { placeHolder: 'Initialize which repo as a Wild West town?' },
  );
  if (!pick) return;
  const cwd = pick.folder.uri.fsPath;

  // ── Verify git repo ───────────────────────────────────────────────────────
  let repoRoot: string;
  try {
    repoRoot = execFileSync('git', ['rev-parse', '--show-toplevel'], { cwd, encoding: 'utf8' }).trim();
  } catch {
    vscode.window.showErrorMessage('Wild West: selected folder is not a git repository.');
    return;
  }

  const repoName = path.basename(repoRoot);
  const wildwestDir = path.join(repoRoot, '.wildwest');
  const log = (msg: string) => outputChannel.appendLine(`[initTown] ${msg}`);
  const git = (args: string[]): string =>
    execFileSync('git', args, { cwd: repoRoot, encoding: 'utf8' }).trim();

  // ── Already initialized ───────────────────────────────────────────────────
  if (fs.existsSync(wildwestDir)) {
    vscode.window.showInformationMessage(`Wild West: '${repoName}' is already initialized.`);
    return;
  }

  // ── Run steps with progress notification ──────────────────────────────────
  let success = false;
  await vscode.window.withProgress(
    { location: vscode.ProgressLocation.Notification, title: 'Wild West v0.4.0: Initializing town…', cancellable: false },
    async (progress) => {
      try {
        // Step 1 — directory structure
        progress.report({ message: 'Creating .wildwest/ structure…' });
        for (const sub of ['telegraph', 'scripts', 'docs']) {
          fs.mkdirSync(path.join(wildwestDir, sub), { recursive: true });
          fs.writeFileSync(path.join(wildwestDir, sub, '.gitkeep'), '');
        }
        log('created .wildwest/ directory structure');

        // Step 2 — registry.json identity block
        progress.report({ message: 'Creating registry.json…' });
        const wwuid = `town-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`;
        let remote = '';
        try {
          remote = git(['config', '--get', 'remote.origin.url']);
        } catch { /* no remote set */ }

        const registry = {
          scope: 'town',
          wwuid,
          alias: repoName,
          remote: remote || null,
          mcp: null,
          createdAt: new Date().toISOString(),
        };

        const registryPath = path.join(wildwestDir, 'registry.json');
        fs.writeFileSync(registryPath, JSON.stringify(registry, null, 2) + '\n');
        log('created registry.json with identity block');

        // Step 3 — _heartbeat branch
        progress.report({ message: 'Setting up _heartbeat branch…' });
        let heartbeatBranchExists = false;
        try {
          git(['rev-parse', '--verify', 'refs/heads/_heartbeat']);
          heartbeatBranchExists = true;
        } catch { /* create it */ }

        if (!heartbeatBranchExists) {
          git(['branch', '_heartbeat', 'HEAD']);
          log('created _heartbeat branch');
        } else {
          log('_heartbeat branch already exists — skipped');
        }

        // Step 4 — _heartbeat worktree
        progress.report({ message: 'Adding _heartbeat worktree…' });
        const worktreePath = path.join(wildwestDir, 'worktrees', '_heartbeat');
        fs.mkdirSync(path.join(wildwestDir, 'worktrees'), { recursive: true });

        try { git(['worktree', 'prune']); } catch { /* ignore */ }

        const wtList = git(['worktree', 'list', '--porcelain']);
        if (!wtList.includes(worktreePath)) {
          git(['worktree', 'add', worktreePath, '_heartbeat']);
          log('added _heartbeat worktree at .wildwest/worktrees/_heartbeat/');
        } else {
          log('_heartbeat worktree already exists — skipped');
        }

        // Step 5 — .gitignore
        progress.report({ message: 'Updating .gitignore…' });
        updateGitignore(repoRoot, ['.wildwest/worktrees/', '.claude/settings.json'], log);

        // Step 6 — .claude/settings.json (Claude Code hook config)
        progress.report({ message: 'Writing .claude/settings.json hook config…' });
        const port = vscode.workspace
          .getConfiguration('wildwest')
          .get<number>('claudeCode.hookPort', 7379);
        writeClaudeSettings(repoRoot, port, log);

        // Step 7 — CLAUDE.md town identity document
        progress.report({ message: 'Generating CLAUDE.md…' });
        const claudeMdPath = path.join(repoRoot, 'CLAUDE.md');
        if (!fs.existsSync(claudeMdPath)) {
          fs.writeFileSync(claudeMdPath, generateClaudeMd({ alias: repoName, wwuid, remote: remote || null }));
          log('created CLAUDE.md (town identity template)');
        } else {
          log('CLAUDE.md already exists — skipped (no overwrite)');
        }

        outputChannel.appendLine('');
        outputChannel.appendLine(`'${repoName}' initialized. Next steps:`);
        outputChannel.appendLine('  1. git add .wildwest/ .gitignore');
        outputChannel.appendLine('  2. git commit');
        outputChannel.appendLine('  3. git push');
        success = true;
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        log(`ERROR: ${msg}`);
        vscode.window.showErrorMessage(`Wild West initTown failed: ${msg}`);
        outputChannel.show();
      }
    },
  );

  // ── Toast — fires after progress notification is fully dismissed ──────────
  if (success) {
    const action = await vscode.window.showInformationMessage(
      `Wild West: '${repoName}' initialized.`,
      'View Log',
    );
    if (action === 'View Log') outputChannel.show();
  }
}

// ---------------------------------------------------------------------------
// initCounty — scaffold a county-level .wildwest/ structure
// ---------------------------------------------------------------------------

export async function initCounty(outputChannel: vscode.OutputChannel): Promise<void> {
  const folders = vscode.workspace.workspaceFolders;
  if (!folders || folders.length === 0) {
    vscode.window.showErrorMessage('Wild West: no workspace folder open.');
    return;
  }

  const pick = await vscode.window.showQuickPick(
    folders.map((f) => ({ label: f.name, description: f.uri.fsPath, folder: f })),
    { placeHolder: 'Initialize which directory as a Wild West county?' },
  );
  if (!pick) return;
  const cwd = pick.folder.uri.fsPath;

  let repoRoot: string;
  try {
    repoRoot = execFileSync('git', ['rev-parse', '--show-toplevel'], { cwd, encoding: 'utf8' }).trim();
  } catch {
    vscode.window.showErrorMessage('Wild West: selected folder is not a git repository.');
    return;
  }

  const repoName = path.basename(repoRoot);
  const wildwestDir = path.join(repoRoot, '.wildwest');
  const log = (msg: string) => outputChannel.appendLine(`[initCounty] ${msg}`);
  const git = (args: string[]): string =>
    execFileSync('git', args, { cwd: repoRoot, encoding: 'utf8' }).trim();

  if (fs.existsSync(wildwestDir)) {
    vscode.window.showInformationMessage(`Wild West: '${repoName}' is already initialized.`);
    return;
  }

  let success = false;
  await vscode.window.withProgress(
    { location: vscode.ProgressLocation.Notification, title: 'Wild West: Initializing county…', cancellable: false },
    async (progress) => {
      try {
        // Step 1 — directory structure
        progress.report({ message: 'Creating .wildwest/ structure…' });
        for (const sub of ['scripts', 'docs']) {
          fs.mkdirSync(path.join(wildwestDir, sub), { recursive: true });
          fs.writeFileSync(path.join(wildwestDir, sub, '.gitkeep'), '');
        }
        createTelegraphDirs(wildwestDir, log);
        log('created .wildwest/ directory structure');

        // Step 2 — registry.json
        progress.report({ message: 'Creating registry.json…' });
        const wwuid = `county-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`;
        let remote = '';
        try { remote = git(['config', '--get', 'remote.origin.url']); } catch { /* no remote */ }

        const registry = {
          scope: 'county',
          schema_version: '2',
          wwuid,
          alias: repoName,
          remote: remote || null,
          mcp: null,
          towns: [],
          createdAt: new Date().toISOString(),
        };
        fs.writeFileSync(path.join(wildwestDir, 'registry.json'), JSON.stringify(registry, null, 2) + '\n');
        log('created registry.json (scope: county)');

        // Step 3 — .gitignore
        progress.report({ message: 'Updating .gitignore…' });
        updateGitignore(repoRoot, ['.claude/settings.json'], log);

        // Step 4 — .claude/settings.json
        progress.report({ message: 'Writing .claude/settings.json hook config…' });
        const port = vscode.workspace.getConfiguration('wildwest').get<number>('claudeCode.hookPort', 7379);
        writeClaudeSettings(repoRoot, port, log);

        // Step 5 — CLAUDE.md
        progress.report({ message: 'Generating CLAUDE.md…' });
        const claudeMdPath = path.join(repoRoot, 'CLAUDE.md');
        if (!fs.existsSync(claudeMdPath)) {
          fs.writeFileSync(claudeMdPath, generateCountyClaudeMd({ alias: repoName, wwuid, remote: remote || null }));
          log('created CLAUDE.md (county identity template)');
        } else {
          log('CLAUDE.md already exists — skipped');
        }

        outputChannel.appendLine('');
        outputChannel.appendLine(`'${repoName}' county initialized. Next steps:`);
        outputChannel.appendLine('  1. Update registry.json towns[] array with known towns');
        outputChannel.appendLine('  2. git add .wildwest/ .gitignore');
        outputChannel.appendLine('  3. git commit && git push');
        success = true;
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        log(`ERROR: ${msg}`);
        vscode.window.showErrorMessage(`Wild West initCounty failed: ${msg}`);
        outputChannel.show();
      }
    },
  );

  if (success) {
    const action = await vscode.window.showInformationMessage(
      `Wild West: '${repoName}' county initialized.`,
      'View Log',
    );
    if (action === 'View Log') outputChannel.show();
  }
}

// ---------------------------------------------------------------------------
// initTerritory — scaffold a territory-level .wildwest/ structure
// ---------------------------------------------------------------------------

export async function initTerritory(outputChannel: vscode.OutputChannel): Promise<void> {
  const folders = vscode.workspace.workspaceFolders;
  if (!folders || folders.length === 0) {
    vscode.window.showErrorMessage('Wild West: no workspace folder open.');
    return;
  }

  const pick = await vscode.window.showQuickPick(
    folders.map((f) => ({ label: f.name, description: f.uri.fsPath, folder: f })),
    { placeHolder: 'Initialize which directory as a Wild West territory (world root)?' },
  );
  if (!pick) return;
  const cwd = pick.folder.uri.fsPath;

  let repoRoot: string;
  try {
    repoRoot = execFileSync('git', ['rev-parse', '--show-toplevel'], { cwd, encoding: 'utf8' }).trim();
  } catch {
    // Territory root may not be a git repo — use the folder directly
    repoRoot = cwd;
  }

  const repoName = path.basename(repoRoot);
  const wildwestDir = path.join(repoRoot, '.wildwest');
  const log = (msg: string) => outputChannel.appendLine(`[initTerritory] ${msg}`);

  if (fs.existsSync(wildwestDir)) {
    vscode.window.showInformationMessage(`Wild West: '${repoName}' is already initialized.`);
    return;
  }

  let success = false;
  await vscode.window.withProgress(
    { location: vscode.ProgressLocation.Notification, title: 'Wild West: Initializing territory…', cancellable: false },
    async (progress) => {
      try {
        // Step 1 — directory structure
        progress.report({ message: 'Creating .wildwest/ structure…' });
        for (const sub of ['scripts', 'docs']) {
          fs.mkdirSync(path.join(wildwestDir, sub), { recursive: true });
          fs.writeFileSync(path.join(wildwestDir, sub, '.gitkeep'), '');
        }
        createTelegraphDirs(wildwestDir, log);
        log('created .wildwest/ directory structure');

        // Step 2 — registry.json
        progress.report({ message: 'Creating registry.json…' });
        const wwuid = `territory-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`;

        const registry = {
          scope: 'territory',
          schema_version: '2',
          wwuid,
          alias: repoName,
          remote: null,
          mcp: null,
          counties: [],
          createdAt: new Date().toISOString(),
        };
        fs.writeFileSync(path.join(wildwestDir, 'registry.json'), JSON.stringify(registry, null, 2) + '\n');
        log('created registry.json (scope: territory)');

        // Step 3 — .gitignore (best-effort — territory may not be a git repo)
        progress.report({ message: 'Updating .gitignore…' });
        updateGitignore(repoRoot, ['.claude/settings.json'], log);

        // Step 4 — .claude/settings.json
        progress.report({ message: 'Writing .claude/settings.json hook config…' });
        const port = vscode.workspace.getConfiguration('wildwest').get<number>('claudeCode.hookPort', 7379);
        writeClaudeSettings(repoRoot, port, log);

        // Step 5 — CLAUDE.md
        progress.report({ message: 'Generating CLAUDE.md…' });
        const claudeMdPath = path.join(repoRoot, 'CLAUDE.md');
        if (!fs.existsSync(claudeMdPath)) {
          fs.writeFileSync(claudeMdPath, generateTerritoryClaudeMd({ alias: repoName, wwuid, remote: null }));
          log('created CLAUDE.md (territory identity template)');
        } else {
          log('CLAUDE.md already exists — skipped');
        }

        outputChannel.appendLine('');
        outputChannel.appendLine(`'${repoName}' territory initialized. Next steps:`);
        outputChannel.appendLine('  1. Update registry.json counties[] array with known counties');
        outputChannel.appendLine('  2. Set worldRoot + countiesDir in VS Code wildwest settings');
        success = true;
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        log(`ERROR: ${msg}`);
        vscode.window.showErrorMessage(`Wild West initTerritory failed: ${msg}`);
        outputChannel.show();
      }
    },
  );

  if (success) {
    const action = await vscode.window.showInformationMessage(
      `Wild West: '${repoName}' territory initialized.`,
      'View Log',
    );
    if (action === 'View Log') outputChannel.show();
  }
}
